---
- name: reload apache
  become: true
  become_user: root
  command: /etc/init.d/apache2 restart

- name: restart nginx
  become: true
  become_user: root
  service:
    name: nginx
    state: restarted

- name: restart exim4
  become: true
  become_user: root
  command: /etc/init.d/exim4 restart

- name: restart php 7.0 processor
  become: true
  become_user: root
  command: systemctl restart php7.0-fpm

- name: restart php 5.6 processor
  become: true
  become_user: root
  command: systemctl restart php5.6-fpm