---
- name: install php
  apt: name=php5 state=present

- name: install php gd
  apt: name=php5-gd state=present

- name: install php mysql
  apt: name=php5-mysql state=present

- name: install php imagemagick
  apt: name=php5-imagick state=present

- name: install php xdebug
  apt: name=php5-xdebug state=present

- name: install php curl
  apt: name=php5-curl state=present

- name: install php sqlite
  apt: name=php5-sqlite state=present

- name: install php memcached
  apt: name=php5-memcached state=present

- name: install php mcrypt
  apt: name=php5-mcrypt state=present

- name: init php.ini for apache
  template:
    src=php5.ini.j2
    dest=/etc/php5/apache2/conf.d/00-php.ini

- name: init php.ini for cli
  template:
    src=php5.ini.j2
    dest=/etc/php5/cli/conf.d/00-php.ini

- name: init xdebug.ini for apache
  template:
    src=xdebug.ini.j2
    dest=/etc/php5/apache2/conf.d/90-xdebug.ini
  notify:
  - reload apache

- name: init xdebug.ini for cli
  template:
    src=xdebug.ini.j2
    dest=/etc/php5/cli/conf.d/90-xdebug.ini

- name: install ioncube for php5.0
  command: "{{ item }}"
  become: true
  become_user: root
  args:
    chdir: /home/vagrant/
  with_items:
    - wget http://downloads3.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64.tar.gz
    - tar xzf ioncube_loaders_lin_x86-64.tar.gz
    - cp /home/vagrant/ioncube/ioncube_loader_lin_5.6.so /usr/lib/php5/20131226
    - rm -rf /home/vagrant/ioncube
    - rm ioncube_loaders_lin_x86-64.tar.gz

- name: init ioncube.ini
  template:
    src=ioncube.ini.j2
    dest=/etc/php5/apache2/conf.d/00-ioncube.ini

- name: init ioncube.ini for cli
  template:
    src=ioncube.ini.j2
    dest=/etc/php5/cli/conf.d/00-ioncube.ini