---
- name: install php7.0
  apt: name=php7.0 state=present

- name: install php7.0-cli
  apt: name=php7.0-cli state=present

- name: install php7.0-mysql
  apt: name=php7.0-mysql state=present

- name: install php7.0-gd
  apt: name=php7.0-gd state=present

- name: install php7.0-imagemagick
  apt: name=php7.0-imagick state=present

- name: install php7.0-xdebug
  apt: name=php7.0-xdebug state=present

- name: install php7.0-curl
  apt: name=php7.0-curl state=present

- name: install php7.0-sqlite3
  apt: name=php7.0-sqlite3 state=present

- name: install php7.0-memcached
  apt: name=php7.0-memcached state=present

- name: install php7.0-mcrypt
  apt: name=php7.0-mcrypt state=present

- name: install php7.0-xml
  apt: name=php7.0-xml state=present

- name: init php.ini for apache
  template:
    src=php7.ini.j2
    dest=/etc/php/7.0/apache2/conf.d/00-php.ini

- name: init php.ini for cli
  template:
    src=php7.ini.j2
    dest=/etc/php/7.0/cli/conf.d/00-php.ini

- name: init xdebug.ini
  template:
    src=xdebug.ini.j2
    dest=/etc/php/7.0/apache2/conf.d/90-xdebug.ini
  notify:
  - reload apache