---
- name: install apt dependencies
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: false
  with_items:
    - apt-transport-https

- name: update apt cache
  apt: update_cache=yes
