---
- name: install java openjdk
  apt: name=default-jdk state=present

#- name: install tomcat7
#  apt: name=tomcat7 state=present

#- name: install tomcat7 admin
#  apt: name=tomcat7-admin state=present

- name: install apache solr
  command: "{{ item }}" 
  with_items:
    - wget http://archive.apache.org/dist/lucene/solr/5.5.0/solr-5.5.0.tgz
    - tar xvf solr-5.5.0.tgz 
    - ./solr-5.5.0/bin/install_solr_service.sh solr-5.5.0.tgz
    - rm solr-5.5.0.tgz
    - rm -rf solr-5.5.0

