---
- name: install imagemagick
  apt: name=imagemagick state=present

- name: install curl
  apt: name=curl state=present

- name: install memcached
  apt: name=memcached state=present

- name: install git
  apt: name=git state=present

- name: install midnight commander
  apt: name=mc state=present

#- name: install npm apt sources
#  shell: curl -sL https://deb.nodesource.com/setup_5.x | bash - creates=/etc/apt/sources.list.d/nodesource.list

#- name: install npm
#  apt: name=npm state=present

#- name: install grunt
#  npm: name=grunt-cli global=yes state=present